version: '3.9'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./:/var/www/
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/var/www/
    restart: unless-stopped
    depends_on:
      - database

  database:
    image: mysql:8.0.30
    restart: unless-stopped
    volumes:
      - ./tmp/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: main
      ### Change pass!
      MYSQL_ROOT_PASSWORD: root
    # ports:
    #   - "3306:3306"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci

  adminer:
    image: adminer
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - 8080:8080
